// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QHQxTsQqLKH4TQ6td-yCUZ-Z3Hkcvls',
    appId: '1:655442033183:web:f116384987f46642b6332a',
    messagingSenderId: '655442033183',
    projectId: 'advmobprog-firebase-eb27c',
    authDomain: 'advmobprog-firebase-eb27c.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-eb27c.firebasestorage.app',
    measurementId: 'G-N482911BN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOtB8gmeveSVdF8WkLt2u9ixDJnJXNSg',
    appId: '1:655442033183:android:a7c21dc3687d1cebb6332a',
    messagingSenderId: '655442033183',
    projectId: 'advmobprog-firebase-eb27c',
    storageBucket: 'advmobprog-firebase-eb27c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZh09JBHTY-RBXVCM6DB7-VKmCfX7Rt7E',
    appId: '1:655442033183:ios:3f28dc9d2464487ab6332a',
    messagingSenderId: '655442033183',
    projectId: 'advmobprog-firebase-eb27c',
    storageBucket: 'advmobprog-firebase-eb27c.firebasestorage.app',
    iosBundleId: 'com.example.floresMobile',
  );
}
